# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mychoice_text', models.CharField(max_length=200)),
                ('myvotes', models.IntegerField(default=0)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.Choice')),
            ],
        ),
    ]
