# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0003_question_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='year_in_school',
        ),
    ]
